"""Add vendido column to produto

Revision ID: d23028fdca67
Revises: 
Create Date: 2025-01-11 05:19:59.642924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23028fdca67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendido', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_venda', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('data_venda')
        batch_op.drop_column('vendido')

    # ### end Alembic commands ###
