"""Adiciona colunas quantidade, vendido e data_venda na tabela Produto

Revision ID: e758a6c9954b
Revises: d23028fdca67
Create Date: 2025-01-11 14:37:16.678425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e758a6c9954b'
down_revision = 'd23028fdca67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=False))
        batch_op.alter_column('vendido',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('data_venda',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('data_venda',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('vendido',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('quantidade')

    # ### end Alembic commands ###
